name: Build check

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ main, develop, release ]

jobs:
  build:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup environment
      run: |
        sudo apt-get update
        sudo apt-get install autoconf automake libtool help2man make lcov
    - name: automake
      run: ./scripts/bootstrap.sh
    - name: native compiler
      run: | 
        ./configure CFLAG="--coverage --no-inline -g3 -O0"
    - name: make
      run: make
    - name: make check
      run: make check
    - if: always()
      name: gcov
      run: |
        ls -l ./; ls -l check/
        gcov check/checkexfat.gcda -p -l
    - if: always()
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: |
          checkexfat.c.gcov
        retention-days: 1
