name: Create Archive

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: create archive
        run: |
          git archive HEAD -o test-`cat VERSION`.tar.gz
          ls -l
      - name: upload to artifact
        run: |
          mkdir -p outputs
          mv ./test-*.tar.gz outputs
      - if: always()
        uses: actions/upload-artifact@v2
        with:
          name: outputs
          path: outputs/test-*.tar.gz
          retention-days: 1

  release:

    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v2
      - name: download all artifacts
        uses: actions/download-artifact@v2
        with:
          name: outputs
      - name: obtain contents
        run: |
          ./scripts/get_changelog.sh ${{ github.ref }} > contents.md
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: "contents.md"
          draft: false
          prerelease: false
      - name: Upload release binaries
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["./test-*.tar.gz"]'
