name: Build check

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ main, develop, release ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: setup environment
      run: |
        sudo apt-get update
        sudo apt-get install autoconf automake libtool help2man make
        gcc --version
    - name: automake
      run: ./scripts/bootstrap.sh
    - name: configure
      run: ./configure CFLAGS=-Werror
    - name: make
      run: make
