name: Build check

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ main, develop, release ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, armhf, arm64]
        include:
        - arch: armhf
          cc: arm-linux-gnueabihf
        - arch: arm64
          cc: aarch64-linux-gnu

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup environment
      run: |
        sudo apt-get update
        sudo apt-get install autoconf automake libtool help2man make
    - name: install cross compiler
      if: ${{ matrix.arch }} != 'amd64'
      run: sudo apt-get install crossbuild-essential-${{ matrix.arch }}
    - name: automake
      run: ./scripts/bootstrap.sh
    - name: configure
      run: ./configure CFLAGS=-Werror --host=${{ matrix.cross }} 
    - name: make
      run: make
