name: C/C++ CI

on:
  push:
    branches: [ master, develop ]  
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: 'amd64'
          - os: ubuntu-latest
            arch: 'arm'
            cross: arm-linux-gnueabihf
          - os: ubuntu-latest
            arch: 'arm64'
            cross: aarch64-linux-gnu

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: setup environment
      run: |
        sudo apt-get update
        sudo apt-get install autoconf automake libtool help2man make expect    
    - name: automake
      run:  script/bootstrap.sh
    - name: setup compiler (for amd64)
      if: ${{ matrix.arch  == 'amd64' }}
      run: |
        ./configure
    - name: setup compiler (for armhf)
      if: ${{ matrix.arch  == 'arm' }}
      run: |
        sudo apt-get install crossbuild-essential-armhf  
        ./configure --host=${matrix.cross}
    - name: setup compiler (for arm64)
      if: ${{ matrix.arch  == 'arm64' }}
      run: |
        sudo apt-get install crossbuild-essential-arm64
        ./configure --host=aarch64-linux-gnu
    - name: make
      run: make        
