name: C/C++ CI

on:
  push:
    branches: [ master, develop ]  
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: 'amd64'
          - os: ubuntu-latest
            arch: 'arm'
          - os: ubuntu-latest
            arch: 'arm64'

    runs-on: ${{ matrix.os }}

    steps:
    - name: debug
      run: |
        echo "${{ matrix }} ==> debug"
        echo "${{ matrix.os }} ==> debug"
        echo "${{ matrix.arch }} ==> debug"
    - name: setup compiler (for armhf)
      if: ${{ matrix.arch  == 'arm' }}
      run: |
        sudo apt-get install crossbuild-essential-armhf  
    - name: setup compiler (for arm64)
      if: ${{ matrix.arch  == 'arm64' }}
      run: |
        echo 'HOGEHOG'
        sudo apt-get install crossbuild-essential-arm64
