name: C/C++ CI

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    name: Build package
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-linux-gnu
          - os: ubuntu-latest
            target: x86_64_linux-gnuebihf-

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: setup environment
      run: |
        sudo apt-get update
        sudo apt-get install autoconf automake libtool help2man make expect exfat-fuse
    - name: automake
      run:  script/bootstrap.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
