name: C/C++ CI

on:
  push:
    branches: [ master, develop ]  
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: 'amd64'
            target: x86_64-linux-gnu
          - os: ubuntu-latest
            arch: 'arm'
            target: x86_64_linux-gnuebihf-
          - os: ubuntu-latest
            arch: 'arm64'
            target: x86_64_linux-gnuebihf-

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: setup environment
      run: |
        sudo apt-get update
        sudo apt-get install autoconf automake libtool help2man make expect
    - name: Set selected color
      run: echo '::set-output name=SELECTED_COLOR::green $matrix'
    - name: debug
      run: |
        echo "${{ matrix }} ==> debug"
    - name: setup compiler (for armhf)
      run: |
      if: ${{ matrix.arch == 'arm' }}
        sudo apt-get install crossbuild-essential-armhf  
    - name: setup compiler (for arm64)
      run: |
      if: ${{ matrix.arch == 'arm64' }}
        echo 'HOGEHOG'
        sudo apt-get install crossbuild-essential-arm64
    - name: automake
      run:  script/bootstrap.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
