name: C/C++ CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

strategy:
  matrix:
    compiler: [gcc, clang]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup environment
      run: |
        sudo apt-get update
        sudo apt-get install autoconf automake libtool help2man make expect
    - name: automake
      run:  script/bootstrap.sh
    - name: configure
	  env:
	    CC: ${{ matrix.compiler }}
      run: ./configure
    - name: make
	  env:
	    CC: ${{ matrix.compiler }}
      run: make
    - name: make check
      run: make check
