# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: setup environment
        run: |
          sudo apt-get update
          sudo apt-get install autoconf automake libtool help2man make dh-make
      - name: automake
        run: ./scripts/bootstrap.sh
      - name: Generate debian package
        run: dpkg-buildpackage -us -uc
      # Runs a single command using the runners shell
      - name: Pbuilder
        run: |
          sudo apt-get install ubuntu-dev-tools
          sudo apt-get install qemu-user-static
          sudo apt-get install curl libarchive-cpio-perl libglib2.0-data libltdl-dev libmail-sendmail-perl lynx shared-mime-info wget xdg-user-dirs 
          pbuilder-dist focal arm64 create
          pbuilder-dist focal arm64 build ../exfat-rawtools_*.dsc
