name: Run Test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        compiler: [gcc, clang]
      
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: setup environment
      run: |
        sudo apt-get update
        sudo apt-get install autoconf automake libtool help2man make expect
    - name: automake
      run:  scripts/bootstrap.sh
    - name: configure
      env:
        CC: ${{ matrix.compiler }}
      run: ./configure
    - name: make
      env:
        CC: ${{ matrix.compiler }}
      run: make

  test:
    continue-on-error: true

    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: check
      run: |
         pwd
         ls -la
         ls -la ../
    - name: make check
      run: make check
    - name: copy
      if: always()
      run: |
         pwd
         ls -la
         mkdir -p ../logs/${{ matrix.compiler }}
         cp ./test-suite.log ../logs/${{ matrix.compiler }}
         ls -la
#        mv tests/*.log ../logs/${{ matrix.compiler }}

  artifact:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - name: check
        run: pwd
      - if: always()
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: |
            logs
          retention-days: 1
