# This is a basic workflow to help you get started with Actions

name: release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  native_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup environment
      run: |
        sudo apt-get update
        sudo apt-get install autoconf automake libtool help2man make dh-make
    - name: automake
      run: ./scripts/bootstrap.sh
    - name: generate Distribution
      run: dpkg-buildpackage -b -us -uc -d -rfakeroot
    - name: move
      run: mv ../*.deb ./
    - name: artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: exfat-rawtools_*_amd64.deb
    - name: clean up
      run: echo "END"

  cross_build:

    strategy:
      matrix:
        arch: [armhf, arm64]

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: output payload
        run: cat $GITHUB_EVENT_PATH

      # Runs a single command using the runners shell
      - name: package install
        run: |
          sudo apt-get update
          sudo apt-get install qemu-user-static debootstrap schroot

      - name: debootstrap
        run: sudo qemu-debootstrap --arch=${{ matrix.arch }} --include=autoconf,automake,libtool,make,dh-make focal /chroot/${{ matrix.arch }} http://ports.ubuntu.com/

      - name: setup schroot
        run: | 
          echo "[${{ matrix.arch }}-ubuntu]
          description=Ubuntu 20.04 focal
          directory=/chroot/${{ matrix.arch }}
          root-users=$(whoami)
          users=$(whoami)
          type=directory" | sudo tee /etc/schroot/chroot.d/${{ matrix.arch }}-ubuntu

      # Runs a set of commands using the runners shell
      - name: Run chroot
        run: |
          cat << EOF |  script -e -c 'schroot -c ${{ matrix.arch }}-ubuntu -p bash -u root' 
          uname -m
          cd $PWD
          ./scripts/bootstrap.sh
          dpkg-buildpackage -b -us -uc -d
          ls -lA ../
          exit
          EOF

      - name: test
        run: mv ../*.deb ./

      - name: artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: exfat-rawtools_*_${{ matrix.arch }}.deb

  release:
    runs-on: ubuntu-latest
    needs: [native_build, cross_build]
    steps:
      - name: test2
        run: echo AA
