# This is a basic workflow to help you get started with Actions

name: release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  native_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup environment
      run: |
        sudo apt-get update
        sudo apt-get install autoconf automake libtool help2man make dh-make
    - name: automake
      run: ./scripts/bootstrap.sh
    - name: generate Distribution
      run: dpkg-buildpackage -b -us -uc -d -rfakeroot
    - name: move
      run: mv ../*.deb ./
    - name: artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: exfat-rawtools_*_amd64.deb
    - name: clean up
      run: echo "END"

  release:
    runs-on: ubuntu-latest
    needs: [native_build]
    steps:
      - uses: actions/checkout@v3
      - name: load dist
        uses: actions/download-artifact@v2
        with:
          name: artifacts

      - name: test
        run: ls -la 
      - name: obtain body
        run: |
          echo "Release ${{ github.ref }}" > body.md
          ./scripts/get_changelog.sh ${{ github.ref }} > body.md
      - name: Create Release
        run: |
          assets=()
          for asset in ./exfat-rawtools_*.deb; do
            assets+=("-a" "$asset")
          done
          tag_name="${GITHUB_REF##*/}"
          hub release create "${assets[@]}" -m "$tag_name" -F body.md "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
