# This is a basic workflow to help you get started with Actions

name: release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  native_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup environment
      run: |
        sudo apt-get update
        sudo apt-get install autoconf automake libtool help2man make dh-make
    - name: automake
      run: ./scripts/bootstrap.sh
    - name: generate Distribution
      run: dpkg-buildpackage -b -us -uc -d -rfakeroot
    - name: Get Name of Artifact
      run: |
        cd ..; ls -lA
    - name: artifacts
      uses: actions/upload-artifact@v2
      with:
        name: amd64
        path: ./*.deb
    - name: clean up
      run: echo "END"

