name: Create Release

on:
#  push:
#    # Sequence of patterns matched against refs/tags
#    tags:
#      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  push:
    branches: [ master, develop ]    

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [amd64, armhf, arm64]

    steps:
      - uses: actions/checkout@v2
      - name: setup environment
        run: |
          sudo apt-get update
          sudo apt-get install autoconf automake libtool help2man make dh-make
          gcc --version
      - name: install cross compiler
        if: ${{ matrix.arch  }} != 'amd64'
        run: |
          sudo apt-get install crossbuild-essential-${{ matrix.arch }}
      - name: automake
        run: ./scripts/bootstrap.sh
      - name: package
        run: dpkg-buildpackage -b -us -uc -d -rfakeroot --host-arch ${{ matrix.arch }}
      - name: mkdir
        run: |
          mkdir -p output
          mv ../debugfatfs_*.deb output
      - if: always()
        uses: actions/upload-artifact@v2
        with:
          name: outputs
          path: output/debugfatfs_*.deb
