name: Perform Test

on:
  push:
    branches: [ main, develop, topic/autotools ]
  pull_request:
    branches: [ main, develop, topic/autotools ]

jobs:
  build_images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup environment
      run: |
        sudo apt-get update
        sudo apt-get install autoconf automake libtool make dh-make
        sudo apt-get install exfatprogs
    - name: automake
      run: ./scripts/bootstrap.sh
    - name: native build
      run: |
        ./configure
        make
        make install
    - name: create sparse files
      run: |
        dd if=/dev/zero of=file.img bs=1 count=0 seek=2T
    - name: create sparsed image
      run: |
        mkfs.exfat file.img
        mkdir mnt
        sudo mount file.img -t exfat -o loop file.img mnt
        sudo mkdir mnt/DIR
        sudo umount mnt
    - name: run
      run: |
        checkexfat file.img
        statfsexfat file.img
        lsexfat file.img /
        statexfat file.img /DIR

