name: Perform Test

on:
  push:
    branches: [ main, develop, topic/autotools ]
  pull_request:
    branches: [ main, develop, topic/autotools ]

jobs:
  build_images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup environment
      run: |
        sudo apt-get update
        sudo apt-get install autoconf automake libtool make dh-make
        sudo apt-get install exfatprogs
    - name: automake
      run: ./scripts/bootstrap.sh
    - name: native build
      run: |
        ./configure
        make
        sudo make install
    - name: create sparse files
      run: |
        dd if=/dev/zero of=file.img bs=1 count=0 seek=2T
    - name: create sparsed image
      run: |
        mkfs.exfat file.img
    - name: run
      run: |
        sudo checkexfat file.img
        sudo statfsexfat file.img
        sudo lsexfat file.img /
